server:
  port: 8889
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/angel/Downloads/configserver/src/main/resources/config